#!/usr/bin/env python
# coding=utf-8

"""
"""

from __future__ import with_statement

import time
import os

TIME_FOR_NEW_WORD = 5

def clear_screen():
    """

    """
    if os.getenv('EMACS'):
        # assume emacs server is running
        os.system('emacsclient --eval \(my-clear-default-shell-buffer\)')
    else:
        if os.name == 'nt':
            os.system('cls')
        else:
            os.system('clear')

def print_correct():
    print "\n                correct."
    time.sleep(0.3)

def print_correction(word, input1, input2):
    print "correct spell: ", word
    print " your 1st try: ", input1
    print " your 2nd try: ", input2
    time.sleep(3.0)

def main():
    """

    """
    DEFAULT_WORD_FILE = '/home/sylecn/projects/lword/words'
    word = ''
    explanation = ''
    wrong_words = []
    count = 0
    with open(DEFAULT_WORD_FILE, 'r') as f:
        clear_screen()
        for line in f:
            if line.startswith('#'):
                continue
            if line != '\n':
                if word:
                    explanation += line
                else:
                    word = line[:-1]
                    count += 1
                    explanation = ''
            else:
                if not word:
                    # ignore empty lines at beginning
                    continue
                # word is read, now print explanation and ask for spelling
                print explanation,
                input1 = raw_input("spell the word: ")
                if input1 == '':
                    # user press enter without trying.
                    #TODO add to new words list
                    print "learn new word\n"
                    print word
                    print explanation
                    time.sleep(TIME_FOR_NEW_WORD)
                    clear_screen()
                    # now it's not new anymore
                    print explanation
                    input1 = raw_input("spell the word: ")
                if input1 != word:
                    wrong_words.append((explanation, word))
                    print "wrong. try again.",
                    input2 = raw_input("spell the word: ")
                    if input2 != word:
                        print_correction(word, input1, input2)
                    else:
                        print_correct()
                else:
                    print_correct()
                clear_screen()
                word = ''

    # go through wrong words
    wrong_count = len(wrong_words)
    # print "-" * 80
    print "grade: %d/%d (%.1f%%)" % (count - wrong_count, count,
                                     100.0 * (count - wrong_count) / count)
    if wrong_words:
        print "now review wrong words."
        while wrong_words:
            new_wrong_words = []
            for (explanation, word) in wrong_words:
                print explanation,
                input1 = raw_input("spell the word: ")
                if input1 == '':
                    # user press enter without trying.
                    #TODO add to new words list
                    print "learn new word\n"
                    print word
                    print explanation
                    time.sleep(TIME_FOR_NEW_WORD)
                    clear_screen()
                    # now it's not new anymore
                    print explanation
                    input1 = raw_input("spell the word: ")
                if input1 != word:
                    new_wrong_words.append((explanation, word))
                    print "wrong. try again.",
                    input2 = raw_input("spell the word: ")
                    if input2 != word:
                        print_correction(word, input1, input2)
                    else:
                        print_correct()
                else:
                    print_correct()
                clear_screen()
            wrong_words = new_wrong_words
        print "done."
    else:
        print "Congratulations!"

if __name__ == '__main__':
    main()
